server:
  port: 10086
  servlet:
    context-path: /isp/v2

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://8.130.14.218:3306/mydb?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: admin
    password: cjwy837..
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    host: smtp.qq.com
    username: ${my.qq}
    password: ${my.pwd}
    protocol: smtp
    port: 587
    default-encoding: UTF-8
    #????
    properties:
      mail:
        #??SSL ????
        smtp:
          ssl:
            #????????ssl
            enable: false
            required: false
          #??debug??????????????????????????????
        debug: true
# testing here
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml


# mail config
my:
  qq: jas0nch@qq.com
  pwd: acrfcoubzikceada


